name: ashton_jones_dev_website
description: My portfolio website.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  url_launcher: ^5.4.10
  googleapis_auth: ^0.2.12
  googleapis: ^0.55.0
  enough_mail: ^0.0.31






dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
  fonts:
    - family: GoogleSansRegular
      fonts:
        - asset: assets/GoogleSansRegular.ttf

