name: ashton_jones_dev_website
description: My portfolio website.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  mailto: ^1.1.0
  url_launcher: ^5.5.3
  flare_flutter: ^2.0.6
  simple_animations: ^2.2.3
  supercharged: ^1.11.1
  google_fonts: ^1.1.1
  syncfusion_flutter_charts: ^18.4.35



  # Workarounds
  universal_platform: ^0.1.3











dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
  fonts:
    - family: GoogleSansRegular
      fonts:
        - asset: assets/GoogleSansRegular.ttf

